runtime: nodejs22
service: default

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65

handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
    secure: always
    expiration: 365d
    http_headers:
      # Cache static assets for 1 year
      Cache-Control: public, max-age=31536000, immutable
  
  # Catch all handler to index.html
  - url: /.*
    secure: always
    static_files: build/index.html
    upload: build/index.html
    http_headers:
      # Don't cache the index.html
      Cache-Control: no-cache, no-store, must-revalidate
